<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HCS.Passwordless.Core\HCS.Passwordless.Core.csproj" />
    <ProjectReference Include="..\..\src\HCS.Passwordless.MagicLink\HCS.Passwordless.MagicLink.csproj" />
    <ProjectReference Include="..\..\src\HCS.Passwordless.Otp\HCS.Passwordless.Otp.csproj" />
    <ProjectReference Include="..\..\src\HCS.Passwordless.WebAuthn\HCS.Passwordless.WebAuthn.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
    <Using Include="NSubstitute" />
    <Using Include="Microsoft.Extensions.Options" />
    <Using Include="Microsoft.Extensions.Caching.Memory" />
    <Using Include="Microsoft.Extensions.Caching.Distributed" />
  </ItemGroup>

</Project>
